### ISSUE TITLE
Unable to use python SDK v0.3

### ISSUE THREAD

**Issue by SameerAjitPatil** [coppeliaMLA/pybarb#12]
Hi,

I tried to setup python code using pybarb v0.3 sdk but package is not getting installed properly as only metadata folder is appearing after installation and not the folder with SDK code in environment library.

Reference Screenshot:
![pybarb_not_working](https://github.com/coppeliaMLA/pybarb/assets/17757149/b1a0f421-30f4-4f93-bb62-451404d19ca7)

**Comment by SameerAjitPatil** [comment]
@coppeliaMLA 
Here are the steps followed.

1. Created new python project
2. set interpreter to use python-3.8
3. Install pybarb using command: pip install pybarb
4. created python class with sample code with getting error "**ModuleNotFoundError: No module named 'pybarb'**"

![image](https://github.com/coppeliaMLA/pybarb/assets/17757149/97c4b088-8657-4c2a-93e0-a6c506348b9f)

**Comment by coppeliaMLA** [comment]
Hi @SameerAjitPatil I've found the issue and fixed it. If you reinstall the package it should now work (you should see it installs pybarb-0.3.2)

Thanks for flagging this!

**Comment by coppeliaMLA** [comment]
That's weird - what do you get for `dir(pb)`?

**Comment by coppeliaMLA** [comment]
V odd - if you go back into your site packages directory you should now see the pybarb folder. Within that there should be the file `pybarb.py`. Do you see it and if so could you attach it to your message. Thanks

**Comment by SameerAjitPatil** [comment]
yes @coppeliaMLA I can see file. Since only file can not be attached, attached herewith is complete zipped pybarb folder.
But code still failing with same error.
[pybarb.zip](https://github.com/coppeliaMLA/pybarb/files/11460108/pybarb.zip)

**Comment by coppeliaMLA** [comment]
Hi @SameerAjitPatil - looks like the package installed correctly. Could you try restarting your python environment (in case there is something in memory that is causing problems)

**Comment by SameerAjitPatil** [comment]
I tried creating new project. Invalidating cache and all possible things. But still getting same error "AttributeError: module 'pybarb' has no attribute 'BarbAPI'"

**Comment by coppeliaMLA** [comment]
Ok thanks, I'm going to try recreating the error on another machine. Bear with me

**Comment by SameerAjitPatil** [comment]
Thanks for quick updates!

**Comment by coppeliaMLA** [comment]
Hi @SameerAjitPatil I recreated the error and I have (fingers crossed) fixed it. Could you try reinstalling the package (you should get version 0.3.3) and giving it a go? Thanks

**Comment by SameerAjitPatil** [comment]
Awesome! Thanks!
This time it worked. I was able to connect.

print(dir(pb)):
value: **_['APIResultSet', 'AdvertisingSpotsResultSet', 'AudiencesByTimeResultSet', 'BarbAPI', 'ProgrammeRatingsResultSet', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'go', 'json', 'np', 'pd', 'pybarb', 're', 'requests', 'sqlalchemy']_**

**Comment by coppeliaMLA** [comment]
No problem at all. Let me know if you run into any more issues. Out of interest, and if you don't mind saying, who do you work for?- just interested to know who is making use of pybarb  and the API

**Comment by SameerAjitPatil** [comment]
I can not disclose much information, but I would like to share that we are working as product developers to create multiple data extractor plugins to make life easy for agencies to work for clients with multiple platform access. 

Really appreciate quick responses and efforts to fix this!. We are good to close this now!

**Comment by coppeliaMLA** [comment]
No problem at all @SameerAjitPatil. That's good to know since since the barb API project is all about innovation!
